file_paths:
  # Step 1: 关键词打标
  step1_input: "input_data.csv"
  step1_output: "output_tagged.csv" # 输出：带大类标签的CSV
  keywords_config: "keywords.yaml"

  # Step 2: LLM分析情感和细分主题
  step2_input: "output_tagged.csv"  # 输入：上一步的输出
  step2_output: "output_topic_sentiment.csv" # 输出：带细分主题和情感的CSV
  topics_config: "topics.yaml"

  # Step 3: 聚合分析与报告生成
  step3_input: "output_topic_sentiment.csv" # 输入：上一步的输出
  step3_output: "final_report.json" # 输出：最终JSON报告

data_columns:
  comment_column_name: "评论" # 评论列名

llm_api:
  api_key: "your-api-key" # LLM API 密钥
  base_url: "https://www.sophnet.com/api/open-apis/v1" # LLM API 基础URL
  tagging_model: "DeepSeek-V3-Fast" # 关键词打标模型
  report_model: "DeepSeek-V3-Fast"  # 报告生成模型

execution:
  max_workers: 2  # 最大并发工作线程数
  retry_attempts: 10 # 最大重试次数
  retry_delay: 5 # 重试延迟（秒）